import { DataSource } from 'typeorm';
import { OrderEntity } from '../entities/order.entity';
import {
  SEED_USER_IDS,
  SEED_ORDER_IDS,
  SEED_ORDER_STATUS_IDS,
  SEED_DELIVERY_TYPE_IDS,
  SEED_PAYMENT_METHOD_IDS,
  SEED_PAYMENT_STATUS_IDS,
  SEED_PROMOTION_IDS,
} from './constants';

export async function seedOrders(dataSource: DataSource): Promise<void> {
  const repo = dataSource.getRepository(OrderEntity);

  type Row = Pick<
    OrderEntity,
    | 'id'
    | 'orderNumber'
    | 'customerId'
    | 'customerName'
    | 'customerPhone'
    | 'deliveryAddress'
    | 'deliveryTypeId'
    | 'statusId'
    | 'paymentMethodId'
    | 'paymentStatusId'
    | 'subtotal'
    | 'discountAmount'
    | 'shippingFee'
    | 'totalAmount'
    | 'promotionId'
    | 'note'
  >;

  const orders: Row[] = [
    // ORD-001: CUST_01, delivery, cash, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_001,
      orderNumber: 'YG-20240315001',
      customerId: SEED_USER_IDS.CUST_01,
      customerName: 'Lê Thị Hoa',
      customerPhone: '0912000001',
      deliveryAddress: '32 Hoàng Diệu, Phường 5, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 115000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 130000,
      promotionId: null,
      note: null,
    },
    // ORD-002: CUST_02, pickup, momo, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_002,
      orderNumber: 'YG-20240315002',
      customerId: SEED_USER_IDS.CUST_02,
      customerName: 'Phạm Minh Tuấn',
      customerPhone: '0912000002',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.MOMO,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 95000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 95000,
      promotionId: null,
      note: 'Cho thêm đá nhé shop',
    },
    // ORD-003: CUST_03, delivery, vnpay, completed, paid — SUMMER10 promo (10%)
    {
      id: SEED_ORDER_IDS.ORD_003,
      orderNumber: 'YG-20240316001',
      customerId: SEED_USER_IDS.CUST_03,
      customerName: 'Nguyễn Thị Lan',
      customerPhone: '0912000003',
      deliveryAddress: '124 Phan Đình Phùng, Phường 2, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.VNPAY,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 145000,
      discountAmount: 14500,
      shippingFee: 15000,
      totalAmount: 145500,
      promotionId: SEED_PROMOTION_IDS.SUMMER_10PCT,
      note: null,
    },
    // ORD-004: CUST_04, delivery, cash, cancelled, unpaid
    {
      id: SEED_ORDER_IDS.ORD_004,
      orderNumber: 'YG-20240316002',
      customerId: SEED_USER_IDS.CUST_04,
      customerName: 'Hoàng Văn Đức',
      customerPhone: '0912000004',
      deliveryAddress: '56 Hai Bà Trưng, Phường 6, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.CANCELLED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 115000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 130000,
      promotionId: null,
      note: 'Huỷ vì không có ai ở nhà',
    },
    // ORD-005: CUST_05, pickup, zalopay, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_005,
      orderNumber: 'YG-20240317001',
      customerId: SEED_USER_IDS.CUST_05,
      customerName: 'Trịnh Thị Thu',
      customerPhone: '0912000005',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.ZALOPAY,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 156000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 156000,
      promotionId: null,
      note: null,
    },
    // ORD-006: CUST_06, delivery, bank_transfer, completed, paid — LOYAL15K
    {
      id: SEED_ORDER_IDS.ORD_006,
      orderNumber: 'YG-20240317002',
      customerId: SEED_USER_IDS.CUST_06,
      customerName: 'Võ Quốc Bảo',
      customerPhone: '0912000006',
      deliveryAddress: '200 Nguyễn Văn Cừ, Phường 9, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.BANK_TRANSFER,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 167000,
      discountAmount: 15000,
      shippingFee: 15000,
      totalAmount: 167000,
      promotionId: SEED_PROMOTION_IDS.LOYAL_15K,
      note: null,
    },
    // ORD-007: CUST_07, delivery, cash, delivering, unpaid
    {
      id: SEED_ORDER_IDS.ORD_007,
      orderNumber: 'YG-20240318001',
      customerId: SEED_USER_IDS.CUST_07,
      customerName: 'Đặng Thị Kim Anh',
      customerPhone: '0912000007',
      deliveryAddress: '45 Lê Lai, Phường 2, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.DELIVERING,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 192000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 207000,
      promotionId: null,
      note: 'Giao trước 12 giờ trưa nhé',
    },
    // ORD-008: CUST_08, pickup, momo, preparing
    {
      id: SEED_ORDER_IDS.ORD_008,
      orderNumber: 'YG-20240318002',
      customerId: SEED_USER_IDS.CUST_08,
      customerName: 'Bùi Thanh Tùng',
      customerPhone: '0912000008',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.PREPARING,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.MOMO,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 169000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 169000,
      promotionId: null,
      note: null,
    },
    // ORD-009: CUST_09, delivery, cash, confirmed, unpaid
    {
      id: SEED_ORDER_IDS.ORD_009,
      orderNumber: 'YG-20240319001',
      customerId: SEED_USER_IDS.CUST_09,
      customerName: 'Lý Ngọc Diễm',
      customerPhone: '0912000009',
      deliveryAddress: '13 Yersin, Phường 10, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.CONFIRMED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 180000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 195000,
      promotionId: null,
      note: 'Để ở cổng nhé',
    },
    // ORD-010: CUST_10, delivery, vnpay, pending, unpaid
    {
      id: SEED_ORDER_IDS.ORD_010,
      orderNumber: 'YG-20240319002',
      customerId: SEED_USER_IDS.CUST_10,
      customerName: 'Phan Thế Vinh',
      customerPhone: '0912000010',
      deliveryAddress: '3 Lý Tự Trọng, Phường 2, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.PENDING,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.VNPAY,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 133000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 148000,
      promotionId: null,
      note: null,
    },
    // ORD-011: CUST_01, pickup, cash, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_011,
      orderNumber: 'YG-20240320001',
      customerId: SEED_USER_IDS.CUST_01,
      customerName: 'Lê Thị Hoa',
      customerPhone: '0912000001',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 165000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 165000,
      promotionId: null,
      note: null,
    },
    // ORD-012: CUST_02, delivery, momo, ready, paid
    {
      id: SEED_ORDER_IDS.ORD_012,
      orderNumber: 'YG-20240320002',
      customerId: SEED_USER_IDS.CUST_02,
      customerName: 'Phạm Minh Tuấn',
      customerPhone: '0912000002',
      deliveryAddress: '7 Nguyễn Chí Thanh, Phường 1, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.READY,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.MOMO,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 182000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 197000,
      promotionId: null,
      note: null,
    },
    // ORD-013: CUST_03, delivery, cash, completed, paid — FREESHIP
    {
      id: SEED_ORDER_IDS.ORD_013,
      orderNumber: 'YG-20240321001',
      customerId: SEED_USER_IDS.CUST_03,
      customerName: 'Nguyễn Thị Lan',
      customerPhone: '0912000003',
      deliveryAddress: '124 Phan Đình Phùng, Phường 2, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 173000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 173000,
      promotionId: SEED_PROMOTION_IDS.FREE_SHIP_150K,
      note: null,
    },
    // ORD-014: guest order (no customer_id), delivery, cash, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_014,
      orderNumber: 'YG-20240321002',
      customerId: null,
      customerName: 'Khách Lẻ',
      customerPhone: '0900000001',
      deliveryAddress: '10 Nguyễn Du, Phường 1, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 90000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 105000,
      promotionId: null,
      note: 'Khách vãng lai',
    },
    // ORD-015: CUST_04, pickup, zalopay, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_015,
      orderNumber: 'YG-20240322001',
      customerId: SEED_USER_IDS.CUST_04,
      customerName: 'Hoàng Văn Đức',
      customerPhone: '0912000004',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.ZALOPAY,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 154000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 154000,
      promotionId: null,
      note: null,
    },
    // ORD-016: CUST_05, delivery, bank_transfer, cancelled, refunded — FLASH20 (20%)
    {
      id: SEED_ORDER_IDS.ORD_016,
      orderNumber: 'YG-20240322002',
      customerId: SEED_USER_IDS.CUST_05,
      customerName: 'Trịnh Thị Thu',
      customerPhone: '0912000005',
      deliveryAddress: '9 Đinh Tiên Hoàng, Phường 1, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.CANCELLED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.BANK_TRANSFER,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.REFUNDED,
      subtotal: 230000,
      discountAmount: 46000,
      shippingFee: 15000,
      totalAmount: 199000,
      promotionId: SEED_PROMOTION_IDS.FLASH_20PCT,
      note: 'Đã hoàn tiền về tài khoản',
    },
    // ORD-017: CUST_06, delivery, cash, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_017,
      orderNumber: 'YG-20240323001',
      customerId: SEED_USER_IDS.CUST_06,
      customerName: 'Võ Quốc Bảo',
      customerPhone: '0912000006',
      deliveryAddress: '200 Nguyễn Văn Cừ, Phường 9, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 190000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 205000,
      promotionId: null,
      note: null,
    },
    // ORD-018: CUST_07, pickup, momo, completed, paid
    {
      id: SEED_ORDER_IDS.ORD_018,
      orderNumber: 'YG-20240323002',
      customerId: SEED_USER_IDS.CUST_07,
      customerName: 'Đặng Thị Kim Anh',
      customerPhone: '0912000007',
      deliveryAddress: null,
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.PICKUP,
      statusId: SEED_ORDER_STATUS_IDS.COMPLETED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.MOMO,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.PAID,
      subtotal: 154000,
      discountAmount: 0,
      shippingFee: 0,
      totalAmount: 154000,
      promotionId: null,
      note: null,
    },
    // ORD-019: CUST_08, delivery, cash, confirmed, unpaid
    {
      id: SEED_ORDER_IDS.ORD_019,
      orderNumber: 'YG-20240324001',
      customerId: SEED_USER_IDS.CUST_08,
      customerName: 'Bùi Thanh Tùng',
      customerPhone: '0912000008',
      deliveryAddress: '77 Khe Sanh, Phường 10, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.CONFIRMED,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.CASH,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 129000,
      discountAmount: 0,
      shippingFee: 15000,
      totalAmount: 144000,
      promotionId: null,
      note: null,
    },
    // ORD-020: CUST_09, delivery, vnpay, pending, unpaid — BIRTHDAY25 (25%)
    {
      id: SEED_ORDER_IDS.ORD_020,
      orderNumber: 'YG-20240324002',
      customerId: SEED_USER_IDS.CUST_09,
      customerName: 'Lý Ngọc Diễm',
      customerPhone: '0912000009',
      deliveryAddress: '13 Yersin, Phường 10, Đà Lạt, Lâm Đồng',
      deliveryTypeId: SEED_DELIVERY_TYPE_IDS.DELIVERY,
      statusId: SEED_ORDER_STATUS_IDS.PENDING,
      paymentMethodId: SEED_PAYMENT_METHOD_IDS.VNPAY,
      paymentStatusId: SEED_PAYMENT_STATUS_IDS.UNPAID,
      subtotal: 195000,
      discountAmount: 48750,
      shippingFee: 15000,
      totalAmount: 161250,
      promotionId: SEED_PROMOTION_IDS.BIRTHDAY_25PCT,
      note: 'Sinh nhật mình hôm nay',
    },
  ];

  for (const order of orders) {
    // Remove any stale row that shares the same order_number but has a different id
    await dataSource.query(`DELETE FROM orders WHERE order_number = $1 AND id != $2`, [
      order.orderNumber,
      order.id,
    ]);
    await repo.upsert(order, ['id']);
  }

  console.log(`[seed] orders — ${orders.length} rows`);
}
